epochs: 300
env: "LunarLanderContinuous-v2"
val_loss: "mse"
clipratio: 0.2
train_iters: 80
batch_size: 10000
gamma: 0.99
lam: 0.95
horizon: 1000
maxkl: 0.01
env_kwargs: {}
early_stop_val: 210.0
reqd_early_stop_epochs: 50