agent_name: Agent6
batch_size: 2500
clipratio: 0.2
env: CartPole-v1
env_kwargs: {}
epochs: 100
gamma: 0.99
horizon: 1000
lam: 0.97
maxkl: 0.01
minibatch_size: 256
seed: 0
train_iters: 75
val_loss: mse
